apiVersion: v1
kind: Pod
metadata:
  name: puppeteer
spec:
  initContainers:
  - name: volume-permissions
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "chmod -R 777 /home/pptruser/scripts"]
    volumeMounts:
    - name: "scripts-dir"
      mountPath: "/home/pptruser/scripts"
  containers:
  - name: puppeteer-container
    image: ntartaglia2271/puppeteer:3.0
    imagePullPolicy: Always
    command: ["sleep"]
    args: ["604800"]
    env:
    - name: URL
      value: "https://www.carrefour.fr"
    - name: SEARCH
      value: "jambon cuit à l'étouffée découenné"
    - name: MONGO_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongodb-secret
          key: mongo-root-password
    - name: MONGO_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongodb-secret
          key: mongo-root-username
    volumeMounts:
    - name: "scripts-dir"
      mountPath: "/home/pptruser/scripts"
  volumes:
    - name: "scripts-dir"
      persistentVolumeClaim:
        claimName: "scripts-pvc"
  restartPolicy: OnFailure
            