apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{},"creationTimestamp":null,"name":"kueue-mutating-webhook-configuration"},"webhooks":[{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"kueue-webhook-service","namespace":"kueue-system","path":"/mutate-batch-v1-job"}},"failurePolicy":"Fail","name":"mjob.kb.io","rules":[{"apiGroups":["batch"],"apiVersions":["v1"],"operations":["CREATE"],"resources":["jobs"]}],"sideEffects":"None"},{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"kueue-webhook-service","namespace":"kueue-system","path":"/mutate-kueue-x-k8s-io-v1beta1-clusterqueue"}},"failurePolicy":"Fail","name":"mclusterqueue.kb.io","rules":[{"apiGroups":["kueue.x-k8s.io"],"apiVersions":["v1beta1"],"operations":["CREATE"],"resources":["clusterqueues"]}],"sideEffects":"None"},{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"kueue-webhook-service","namespace":"kueue-system","path":"/mutate-kueue-x-k8s-io-v1beta1-resourceflavor"}},"failurePolicy":"Fail","name":"mresourceflavor.kb.io","rules":[{"apiGroups":["kueue.x-k8s.io"],"apiVersions":["v1beta1"],"operations":["CREATE"],"resources":["resourceflavors"]}],"sideEffects":"None"},{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"kueue-webhook-service","namespace":"kueue-system","path":"/mutate-kueue-x-k8s-io-v1beta1-workload"}},"failurePolicy":"Fail","name":"mworkload.kb.io","rules":[{"apiGroups":["kueue.x-k8s.io"],"apiVersions":["v1beta1"],"operations":["CREATE","UPDATE"],"resources":["workloads"]}],"sideEffects":"None"},{"admissionReviewVersions":["v1"],"clientConfig":{"service":{"name":"kueue-webhook-service","namespace":"kueue-system","path":"/mutate-kubeflow-org-v2beta1-mpijob"}},"failurePolicy":"Fail","name":"mmpijob.kb.io","rules":[{"apiGroups":["kubeflow.org"],"apiVersions":["v2beta1"],"operations":["CREATE"],"resources":["mpijobs"]}],"sideEffects":"None"}]}
  creationTimestamp: "2023-04-26T10:23:19Z"
  generation: 1
  name: kueue-mutating-webhook-configuration
  resourceVersion: "8029"
  uid: 23be695b-4050-4737-8952-106c5cc7588e
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kueue-webhook-service
      namespace: kueue-system
      path: /mutate-batch-v1-job
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mjob.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - batch
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - jobs
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kueue-webhook-service
      namespace: kueue-system
      path: /mutate-kueue-x-k8s-io-v1beta1-clusterqueue
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mclusterqueue.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - kueue.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    resources:
    - clusterqueues
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kueue-webhook-service
      namespace: kueue-system
      path: /mutate-kueue-x-k8s-io-v1beta1-resourceflavor
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mresourceflavor.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - kueue.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    resources:
    - resourceflavors
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kueue-webhook-service
      namespace: kueue-system
      path: /mutate-kueue-x-k8s-io-v1beta1-workload
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mworkload.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - kueue.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workloads
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kueue-webhook-service
      namespace: kueue-system
      path: /mutate-kubeflow-org-v2beta1-mpijob
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mmpijob.kb.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - kubeflow.org
    apiVersions:
    - v2beta1
    operations:
    - CREATE
    resources:
    - mpijobs
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
