kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: webscrap
#networking:
  # the default CNI will not be installed
  #disableDefaultCNI: true
nodes:
- role: control-plane
  #extraMounts:
  #- hostPath: /c/webscraping/poc/poc-webscraping/plugins/bin
  #  containerPath: /opt/cni/bin
- role: worker
  extraPortMappings:
    - containerPort: 27017
      hostPort: 27017
      # optional: set the bind address on the host
      # 0.0.0.0 is the current default
      listenAddress: "127.0.0.1"
      # optional: set the protocol to one of TCP, UDP, SCTP.
      # TCP is the default
      protocol: TCP