apiVersion: batch/v1
kind: Job
metadata:
  name: puppeteer-117
  namespace: webscraping
  labels:
    kueue.x-k8s.io/queue-name: webscraping-queue
spec:
  ttlSecondsAfterFinished: 20
  suspend: true
  template:
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "chmod -R 777 /home/pptruser/scripts"]
        resources:
          requests:
            cpu: 100m
            memory: "100Mi"
        volumeMounts:
        - name: "scripts-dir"
          mountPath: "/home/pptruser/scripts"
      containers:
      - name: puppeteer-container
        image: ntartaglia2271/puppeteer:3.0
        imagePullPolicy: Always
        command: ["node"]
        args: ["/home/pptruser/scripts/poc-auchan.js"]
        resources:
          requests:
            cpu: 1
            memory: "1Gi"
        env:
        - name: JOB
          value: "117"
        - name: DISTRIBUTEUR
          value: "Auchan"
        - name: URL
          value: "https://www.auchan.fr"
        - name: SEARCH
          value: "3560071186685"
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        volumeMounts:
        - name: "scripts-dir"
          mountPath: "/home/pptruser/scripts"
      restartPolicy: Never
      volumes:
      - name: "scripts-dir"
        persistentVolumeClaim:
          claimName: "scripts-pvc"
      
            