apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scripts-pvc
  namespace: webscraping
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce 
  volumeName: scripts-pv
  resources:
    requests:
      storage: 1Gi