apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: webscraping
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce 
  volumeName: db-pv
  resources:
    requests:
      storage: 1Gi
  
