apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: webscraping-lg-1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"