apiVersion: batch/v1
kind: Job
metadata:
  name: puppeteer-2
  namespace: webscraping
spec:
  ttlSecondsAfterFinished: 20
  backoffLimit: 0
  template:
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "chmod -R 777 /home/pptruser/scripts"]
        volumeMounts:
        - name: "scripts-dir"
          mountPath: "/home/pptruser/scripts"
      containers:
      - name: puppeteer-container
        image: ntartaglia2271/puppeteer:3.0
        imagePullPolicy: Always
        command: ["node"]
        args: ["/home/pptruser/scripts/webscrap.js"]
        env:
        - name: URL
          value: "https://www.carrefour.fr"
        - name: SEARCH
          value: "jambon herta cuit à l'étouffée sel réduit"
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        volumeMounts:
        - name: "scripts-dir"
          mountPath: "/home/pptruser/scripts"
      restartPolicy: Never
      volumes:
      - name: "scripts-dir"
        persistentVolumeClaim:
          claimName: "scripts-pvc"
      
            